ci: deploy integration TK for develop cluster
kubeshop/helm-charts pull request #567
Opened 2023-07-05 14:02 UTC by ypoplavs

## Pull request description
Deploy Stage Testkube to Develop cluster 

## Checklist (choose whats happened)

- [ ] breaking change! (describe)
- [ ] tested locally
- [ ] tested on cluster
- [ ] added new dependencies
- [ ] updated the docs
- [ ] added a test

## Breaking changes

-

## Changes

-

## Fixes

-

2023-07-12 14:05 UTC, ypoplavs commented
@tkonieczny can you please check if namespaces are passed correctly to tests commands?

2023-07-12 14:19 UTC, vsukhin approved these changes

2023-07-13 09:24 UTC, tkonieczny commented on .github/workflows/helm-deploy-testkube-charts-stage.yaml
> +        run: chmod +x ./test/scripts/executor-tests/run.sh && ./test/scripts/executor-tests/run.sh -d -c -s # (delete, create, schedule) - don't execute ## needs optional namespace
Namespace is missing for run script.
`-n NAMESPACE_NAME`

2023-07-13 10:28 UTC, tkonieczny requested changes

2023-07-13 10:28 UTC, tkonieczny commented on .github/workflows/helm-deploy-testkube-charts-stage.yaml
> +        run: chmod +x ./test/scripts/executor-tests/run.sh && ./test/scripts/executor-tests/run.sh -d -c -s --namespace ${{ env.DEPLOYMENT_NAME }} # (delete, create, schedule) - don't execute
`-n` is required for the run script

2023-07-13 11:23 UTC, merged