Added jobs cluster role which was not defined anywhere in helm charts…
kubeshop/helm-charts pull request #57
Opened 2021-11-11 16:33 UTC by fog1985

…. Probably created manually

## Pull request description 

## Checklist (choose whats happened)

- [ ] breaking change! (describe)
- [ ] tested locally
- [ ] tested on cluster
- [ ] added new dependencies
- [ ] updated the docs
- [ ] added a test

## Breaking changes

-

## Changes

-

## Fixes

-

2021-11-11 17:14 UTC, jasmingacic approved these changes

2021-11-11 18:51 UTC, nicufk approved these changes

2021-11-12 05:50 UTC, exu requested changes
Already exists in https://github.com/kubeshop/helm-charts/blob/main/charts/api-server/templates/role.yaml#L29

2021-11-12 06:59 UTC, closed without merging

2021-11-12 06:59 UTC, fog1985 commented
It turned out that this role already exists and described in the taml.