feat(testkube): add custom labels and annotations through testkube-api helm chart
kubeshop/helm-charts pull request #694
Opened 2023-12-21 19:02 UTC by manidharanupoju24

## Pull request description 

## Checklist (choose whats happened)

- [ ] breaking change! (describe)
- [x] tested locally
- [ ] tested on cluster
- [ ] added new dependencies
- [ ] updated the docs
- [ ] added a test

## Breaking changes

-

## Changes

-

## Fixes

-

2023-12-21 19:15 UTC, spkane commented
Relates to: https://github.com/kubeshop/helm-charts/issues/695

2023-12-31 13:35 UTC, vsukhin requested changes
job template structture van't be changed

2024-01-02 17:52 UTC, spkane commented
@vsukhin, Can you provide a bit more detail on your thinking here?

Although this isn't our ideal approach, we did this precisely because it would not impact end users. Users can still override the job template. This makes it possible to pass helm values into the labels and annotations sections of the default job template when the user doesn't override the whole thing.

A better option might be to make it possible to pass in annotations and labels that one wants in the job templates to the operator as env vars and have it use standard go templating to apply them, but that requires touching the code, which we were trying to avoid for this particular workaround.

2024-01-05 12:24 UTC, vsukhin commented
my main concern is that job template definition is splitted between template itself and configmap. so, it's no more self sufficient. I understand, that's a wroking hack, but it's not universal

2024-01-16 19:44 UTC, fulgas commented
This is relevant when you are using linkerd as service mesh. The jobs will not terminate unless you disable the linkerd injection.

2024-01-16 21:17 UTC, spkane commented
@fulgas You might want to add that onto the core issue related to this: https://github.com/kubeshop/helm-charts/issues/695

2025-10-16 09:25 UTC, closed without merging