Tyatsurak/feature/kusk gateway 63
kubeshop/helm-charts pull request #73
Opened 2021-11-19 16:46 UTC by Tarick

## Pull request description 

Kusk Gateway chart

## Checklist (choose whats happened)

- [ ] breaking change! (describe)
- [x] tested locally
- [ ] tested on cluster
- [ ] added new dependencies
- [ ] updated the docs
- [ ] added a test

## Breaking changes

-

## Changes

1. Adds kusk-gateway and kusk-gateway-envoyfleet charts. Kusk gateway chart has subchart with CRDs due to the problem of installing and uninstalling CRDs with helm. kusk-gateway-envoyfleet chart is needed since the CR resource can't be installed with Helm until CRDs are installed and Helm can validate the resource. Specifying ```--disable-openapi-validation``` doesn't help here.
Common variables are passed from main chart to subchart with templates in _helpers - this way we can still use values.yaml variables in template generation and not use "global" variables block.

2. Changes release workflow to separate flows for Testkube and Kusk Gateway. This potentially can cause simultaneous runs, maybe we can trigger Testkube tests workflows separately with [workflow_run](https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows#workflow_run)? @fog1985 

## Fixes

-

2021-11-19 16:56 UTC, kylehodgetts requested changes
The content looks great! Just Github complaining about new lines in the YAML files

2021-11-19 16:56 UTC, kylehodgetts commented on charts/kusk-gateway-envoyfleet/templates/_helpers.tpl
> +{{- end }}
newline

2021-11-19 16:56 UTC, kylehodgetts commented on charts/kusk-gateway-envoyfleet/templates/envoyFleet.yaml
> +  size: {{ .Values.size }}
newline

2021-11-19 16:56 UTC, kylehodgetts commented on charts/kusk-gateway-envoyfleet/values.yaml
> +size: 1
newline

2021-11-19 16:56 UTC, kylehodgetts commented on charts/kusk-gateway/charts/kusk-gateway-crds/values.yaml
> +fullnameOverride: ""
newline

2021-11-19 16:56 UTC, kylehodgetts commented on charts/kusk-gateway/templates/certmanagement.yaml
> +{{- end -}}
newline

2021-11-19 16:56 UTC, kylehodgetts commented on charts/kusk-gateway/templates/deployment.yaml
> +          secretName: "{{ include "kusk-gateway.webhooksCertificate" . }}"
newline

2021-11-19 16:56 UTC, kylehodgetts commented on charts/kusk-gateway/templates/poddisruptionbudget.yaml
> +{{- end }}
newline

2021-11-19 16:56 UTC, kylehodgetts commented on charts/kusk-gateway/templates/rolebinding.yaml
> +{{- end -}}
newline

2021-11-19 16:56 UTC, kylehodgetts commented on charts/kusk-gateway/templates/roles.yaml
> +{{- end -}}
newline

2021-11-19 16:56 UTC, kylehodgetts commented on charts/kusk-gateway/templates/service.yaml
> +{{- end -}}
newline

2021-11-19 16:56 UTC, kylehodgetts commented on charts/kusk-gateway/templates/serviceaccount.yaml
> +{{- end }}
newline

2021-11-19 16:56 UTC, kylehodgetts commented on charts/kusk-gateway/templates/webhooks.yaml
> +{{- end -}}
newline

2021-11-19 16:56 UTC, kylehodgetts commented on charts/kusk-gateway/values.yaml
> +podDisruptionBudget: {}
newline

2021-11-19 18:33 UTC, kylehodgetts approved these changes
Preliminarily approved. Will test on Monday 👍 
Good work!

2021-11-22 08:28 UTC, dobegor approved these changes

2021-11-22 08:51 UTC, fog1985 approved these changes
LGTM

2021-11-22 09:40 UTC, merged